---
# 1️⃣ MySQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "Test@123"
            - name: MYSQL_DATABASE
              value: "bankappdb"
            - name: MYSQL_USER
              value: "bankuser"
            - name: MYSQL_PASSWORD
              value: "bankpass"
---
# 2️⃣ MySQL Service
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
---
# 3️⃣ BankApp Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bankapp
  template:
    metadata:
      labels:
        app: bankapp
    spec:
      containers:
        - name: bankapp
          image: mumairask750/bankapp:latest   # tumhara dockerhub image
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/bankappdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
            - name: SPRING_DATASOURCE_USERNAME
              value: bankuser
            - name: SPRING_DATASOURCE_PASSWORD
              value: bankpass
---
# 4️⃣ BankApp Service (NodePort for Minikube)
apiVersion: v1
kind: Service
metadata:
  name: bankapp-service
spec:
  type: NodePort
  selector:
    app: bankapp
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30007   # Access via minikube service
